name: Deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Copy userLoad.user.js to dist
      run: cp userLoad.user.js dist/

    - name: Copy css to dist
      run: cp scr/Static/css/* dist/

    - name: Copy Assets Audio to dist
      run: mkdir -p dist/Assets/Audio/ && cp -r scr/Static/Assets/Audio/* dist/Assets/Audio/

    - name: Copy Assets Img to dist
      run: mkdir -p dist/Assets/Img/ && cp -r scr/Static/Assets/Img/* dist/Assets/Img/  

    - name: Deploy main to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./dist
        destination_dir: main
